Add snippet for weblinc adapter.js
weblinc/snippets pull request #1
Opened 2016-10-07 17:37 UTC by JakeBeresford

Added a new snippet to for adapter js files

2016-10-07 18:16 UTC, mupt reviewed
You may want to include a pattern for including current_user data in your callback.  That is a frequent requirement of these adapters.

'addToCart': function () {
var addToCartEvent = function (payload) {
}
WEBLINC.currentUser.gettingUserData.done(_.partial(addToCartEvent);
) 
}

2016-10-07 18:22 UTC, meowsus requested changes

2016-10-07 18:22 UTC, meowsus commented on weblinc-js-adapter.sublime-snippet
> +                return script.src.match(/someregexthatmatchesyour3rdpartyscript/i);
`someregexthatmatchesyour3rdpartyscript` should be `${3:someregexthatmatchesyour3rdpartyscript}`

2016-10-07 18:22 UTC, meowsus commented on weblinc-js-adapter.sublime-snippet
> +                return script.src.match(/someregexthatmatchesyour3rdpartyscript/i);
obvs you'll have to increment the other `${n:...}` accordingly

2016-10-07 18:22 UTC, meowsus commented on weblinc-js-adapter.sublime-snippet
> +        ${4:// Base callbacks - remove any that you do not need}
I think this is superfluous.

2016-10-07 18:22 UTC, meowsus commented on weblinc-js-adapter.sublime-snippet
> +  <tabTrigger>wl-adapter</tabTrigger>
Let's change this to `wl-js-analytics-adapter`

I'm about to namespace the others in this branch.

2016-10-07 18:22 UTC, meowsus commented
Also, I like FM's idea.

2016-10-08 22:33 UTC, meowsus commented on wl-js-analytics-adapter.sublime-snippet
> +                return script.src.match(WEBLINC.config.${1:adapterName}.scriptRegex);
If this is 1-to-1, meaning that this adapter is a client for only one third party, i think that adding config is an additional step that isn't needed. 

Thoughts?

2016-10-08 22:33 UTC, meowsus commented on wl-js-analytics-adapter.sublime-snippet
> +                return script.src.match(WEBLINC.config.${1:adapterName}.scriptRegex);
Also, any thoughts around FMs idea to add support for the currentUser promise?

2016-10-08 22:40 UTC, JakeBeresford commented on wl-js-analytics-adapter.sublime-snippet
> +                return script.src.match(WEBLINC.config.${1:adapterName}.scriptRegex);
I guess it depends what the adapter is doing, and what information is required for the integration. My thought here was that there may be API keys, APP ID etc. I used a config for the personalized messaging / free shipping thing and thought it was a good idea. Happy to remove it if that's the consensus.

I'd like to include support for currentUser, I'm will check out how others have implemented it to find the nicest solution. Is there a 'best practice' way to access currentUser?

2016-11-14 16:14 UTC, meowsus requested changes

2016-11-14 16:14 UTC, meowsus commented on wl-js-analytics-adapter.sublime-snippet
> +                return script.src.match(/{3:someregexthatmatchesyour3rdpartyscript}/i);
You didn't increment the numbers that follow. Line 38 (for example) also is a "3".

2016-11-14 16:14 UTC, meowsus commented on wl-js-analytics-adapter.sublime-snippet
> +                return script.src.match(/{3:someregexthatmatchesyour3rdpartyscript}/i);
Should be proceeded by a `$`

2017-03-05 18:56 UTC, merged